### ISSUE TITLE
Missing pyqt dependency in 3.2.2-1 linux64 build

### ISSUE THREAD

**Issue by MaozGelbart** [conda-forge/matplotlib-feedstock#253]
Recent matplotlib build (linux-64/matplotlib-3.2.2-1) for linux64 is missing pyqt dependency. This results in travis failed builds due to missing pyqt dependency. Is this intentional? The prior build (linux-64/matplotlib-3.2.2-0) had pyqt dependency.

**Comment by MaozGelbart** [comment]
@isuruf @tacaswell this possibly changed here [https://github.com/conda-forge/matplotlib-feedstock/pull/247/commits/20dcddabe03c0052d06e4a2c4975cf7af4e78845](https://github.com/conda-forge/matplotlib-feedstock/pull/247/commits/20dcddabe03c0052d06e4a2c4975cf7af4e78845) ?

**Comment by dopplershift** [comment]
Are you still seeing this with the 3.3.x packages?

**Comment by MaozGelbart** [comment]
Indeed, currently all 3.3.x linux64 builds are missing pyqt dependency.

**Comment by dopplershift** [comment]
This should be fixed in the new builds that includes Python 3.9 (#266). The issue was that the matplotlib package was marked `noarch:python`, but that was incorrect due to the selector for whether to depend on pyqt. Since as noarch there would only be a single version on the server, it was a race which one would build and upload first. Fixed by removing `noarch:python`.
